Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalCompras.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult indexlogueado()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

Controllers/LicitacioneController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PortalCompras.Models;

namespace PortalCompras.Controllers
{
    public class LicitacioneController : Controller
    {
        private PortalComprasEntities db = new PortalComprasEntities();

        // GET: Licitacione
        public ActionResult Index()
        {
            var licitaciones = db.Licitaciones.Include(l => l.Licitador).Include(l => l.Producto);
            return View(licitaciones.ToList());
        }

        // GET: Licitacione/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Licitacione licitacione = db.Licitaciones.Find(id);
            if (licitacione == null)
            {
                return HttpNotFound();
            }
            return View(licitacione);
        }

        // GET: Licitacione/Create
        public ActionResult Create()
        {
            ViewBag.IdLicitador = new SelectList(db.Licitadors, "IdLicitador", "NombreLicitador");
            ViewBag.IdProducto = new SelectList(db.Productoes, "IdProducto", "NombreProducto");
            return View();
        }

        // POST: Licitacione/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdLicitacion,NombreLicitacion,IdLicitador,FechaCreacionLicitacion,FechaCierreLicitacion,FechaAdjudicacionLicitacion,ObservacionesLicitacion,IdProducto")] Licitacione licitacione)
        {
            if (ModelState.IsValid)
            {
                db.Licitaciones.Add(licitacione);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdLicitador = new SelectList(db.Licitadors, "IdLicitador", "NombreLicitador", licitacione.IdLicitador);
            ViewBag.IdProducto = new SelectList(db.Productoes, "IdProducto", "NombreProducto", licitacione.IdProducto);
            return View(licitacione);
        }

        // GET: Licitacione/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Licitacione licitacione = db.Licitaciones.Find(id);
            if (licitacione == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLicitador = new SelectList(db.Licitadors, "IdLicitador", "NombreLicitador", licitacione.IdLicitador);
            ViewBag.IdProducto = new SelectList(db.Productoes, "IdProducto", "NombreProducto", licitacione.IdProducto);
            return View(licitacione);
        }

        // POST: Licitacione/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdLicitacion,NombreLicitacion,IdLicitador,FechaCreacionLicitacion,FechaCierreLicitacion,FechaAdjudicacionLicitacion,ObservacionesLicitacion,IdProducto")] Licitacione licitacione)
        {
            if (ModelState.IsValid)
            {
                db.Entry(licitacione).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdLicitador = new SelectList(db.Licitadors, "IdLicitador", "NombreLicitador", licitacione.IdLicitador);
            ViewBag.IdProducto = new SelectList(db.Productoes, "IdProducto", "NombreProducto", licitacione.IdProducto);
            return View(licitacione);
        }

        // GET: Licitacione/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Licitacione licitacione = db.Licitaciones.Find(id);
            if (licitacione == null)
            {
                return HttpNotFound();
            }
            return View(licitacione);
        }

        // POST: Licitacione/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Licitacione licitacione = db.Licitaciones.Find(id);
            db.Licitaciones.Remove(licitacione);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrganismoLicitantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PortalCompras.Models;

namespace PortalCompras.Controllers
{
    public class OrganismoLicitantesController : Controller
    {
        private PortalComprasEntities db = new PortalComprasEntities();

        // GET: OrganismoLicitantes
        public ActionResult Index()
        {
            return View(db.OrganismoLicitantes.ToList());
        }

        // GET: OrganismoLicitantes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrganismoLicitante organismoLicitante = db.OrganismoLicitantes.Find(id);
            if (organismoLicitante == null)
            {
                return HttpNotFound();
            }
            return View(organismoLicitante);
        }

        // GET: OrganismoLicitantes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrganismoLicitantes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdOrganismoLicitante,NombreOrganismoLicitante,ContactoOrganismoLicitante,DireccionOrganismoLicitante")] OrganismoLicitante organismoLicitante)
        {
            if (ModelState.IsValid)
            {
                db.OrganismoLicitantes.Add(organismoLicitante);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organismoLicitante);
        }

        // GET: OrganismoLicitantes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrganismoLicitante organismoLicitante = db.OrganismoLicitantes.Find(id);
            if (organismoLicitante == null)
            {
                return HttpNotFound();
            }
            return View(organismoLicitante);
        }

        // POST: OrganismoLicitantes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdOrganismoLicitante,NombreOrganismoLicitante,ContactoOrganismoLicitante,DireccionOrganismoLicitante")] OrganismoLicitante organismoLicitante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organismoLicitante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organismoLicitante);
        }

        // GET: OrganismoLicitantes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrganismoLicitante organismoLicitante = db.OrganismoLicitantes.Find(id);
            if (organismoLicitante == null)
            {
                return HttpNotFound();
            }
            return View(organismoLicitante);
        }

        // POST: OrganismoLicitantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrganismoLicitante organismoLicitante = db.OrganismoLicitantes.Find(id);
            db.OrganismoLicitantes.Remove(organismoLicitante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PortalCompras.Models;

namespace PortalCompras.Controllers
{
    public class ProductoController : Controller
    {
        private PortalComprasEntities db = new PortalComprasEntities();

        // GET: Producto
        public ActionResult Index()
        {
            return View(db.Productoes.ToList());
        }

        // GET: Producto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProducto,NombreProducto,DescripcionProducto")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Productoes.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(producto);
        }

        // GET: Producto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProducto,NombreProducto,DescripcionProducto")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productoes.Find(id);
            db.Productoes.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>

    <p>PROYECTO UAI</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        <br />
        <br />
        <strong title="Phone">Telefono:</strong>
    3410000000
</address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@portaldecompras.com">Support@portaldecompras.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@portaldecompras.com">Marketing@portaldecompras.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Portal de compras";
}

  
    <body>
        
       <section class="min-h-screen pb-[1.875rem] pt-[calc(var(--header-height)_+_1.875rem)] desktop:py-[unset] bg-[length:100%_100%] bg-no-repeat bg-tertiary flex items-center">
          

            <div class="mx-auto h-full w-full max-w-[1440px] px-[var(--container-padding)] py-0">

          <article class="grid desktop:grid-cols-2 desktop:items-center gap-[60px]">
                 
          <section class="flex justify-center desktop:justify-end">
            <div class="relative z-[1]">
              <img class="h-full w-full" width="327" height="332" src="https://cdn.intiza.com/content/web2/public/images/sections/solutions/user-with-tablet-1.png" alt="Persona mirando una tablet">
             </div>
           </section>
          </article>

            </div>

        </section>
       <main class="bg-gray-light">

           <section class="py-10 desktop:py-[4.25rem]">
               <div class="mx-auto h-full w-full max-w-[1440px] px-[var(--container-padding)] py-0">


                   <ul id="hero-list" class="flex flex-col gap-12">
                       <li>
                           <article class="grid desktop:grid-cols-2 desktop:items-center gap-[60px]">
                               <section>
                                   <div class="mb-2 flex items-center gap-2 desktop:mb-5">

                                       <h3 class="font-medium tracking-[-0.02em] text-[1.625rem] desktop:text-3xl desktop:leading-[38px] text-black" slot="title">
                                           Servicio al Proveedor
                                       </h3>
                                   </div>
                                   <div class="mb-5 desktop:mb-11">
                                       <p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           Ofrezca a sus Proveedores un Portal Online de auto-consulta y
                                       </p><p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           auto-gestión 24x7. Esto además le permitiría liberar tiempos de
                                       </p><p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           sus equipos internos.
                                       </p>
                                   </div>

                               </section>
                           </article>
                       </li>
                       <li>
                           <article class="grid desktop:grid-cols-2 desktop:items-center gap-[60px]">
                               <section class="desktop:order-last">
                                   <div class="mb-2 flex items-center gap-2 desktop:mb-5">

                                       <h3 class="font-medium tracking-[-0.02em] text-[1.625rem] desktop:text-3xl desktop:leading-[38px] text-black" slot="title">
                                           Eficiencia operativa
                                       </h3>
                                   </div>
                                   <div class="mb-5 desktop:mb-11">
                                       <p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           Simplifique la labor de sus equipos internos con automatizaciones, workflows de aprobación online y reglas de negocio.
                                       </p>
                                   </div>
                                   <div class="flex gap-4">

                                       <astro-island uid="1QO0XL" component-url="/_astro/DemoDialogButton.381c695d.js" component-export="DemoDialogButton" renderer-url="/_astro/client.7d9d6d8c.js" props="{&quot;showIcon&quot;:[0,true],&quot;kind&quot;:[0,&quot;supplier-management&quot;],&quot;className&quot;:[0,&quot;!p-0&quot;],&quot;color&quot;:[0,&quot;tertiary&quot;],&quot;variant&quot;:[0,&quot;text&quot;]}" ssr="" client="only" opts="{&quot;name&quot;:&quot;DemoDialogButton&quot;,&quot;value&quot;:&quot;react&quot;}"></astro-island>

                                   </div>
                               </section>

                           </article>
                       </li>
                       <li>
                           <article class="grid desktop:grid-cols-2 desktop:items-center gap-[60px]">
                               <section>
                                   <div class="mb-2 flex items-center gap-2 desktop:mb-5">

                                       <h3 class="font-medium tracking-[-0.02em] text-[1.625rem] desktop:text-3xl desktop:leading-[38px] text-black" slot="title">
                                           Transparencia
                                       </h3>
                                   </div>
                                   <div class="mb-5 desktop:mb-11">
                                       <p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           Logre mayor transparencia en su proceso de compras y pago a
                                       </p><p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           proveedores, dejando registros y pistas de auditoría para cada una
                                       </p><p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                                           de las actividades.
                                       </p>
                                   </div>

                               </section>

                           </article>
                       </li>
                   </ul>


               </div>
           </section>
           <section class="py-11 text-white desktop:py-24 bg-green">

               <div class="grid gap-10 desktop:grid-cols-3 desktop:gap-5">

                   <p class="text-base font-normal tracking-[-0.01em] text-black text-gray">
                       Cuente con una plataforma online donde gestionar sus procesos de evaluación periódica de Proveedores.
                   </p>

               </div>

           </section>
           <section class="py-11 desktop:py-24 bg-[#F4F9F6]">
               <div class="mx-auto h-full w-full max-w-[1440px] px-[var(--container-padding)] py-0">

                   <article class="flex flex-col gap-8 desktop:gap-12">

                       <div class="mb-5 desktop:mb-11">
                           <p class="text-base font-normal tracking-[-0.01em] text-black text-gray">

                               En Portal de compras somos conscientes que gestionamos información confidencial de
                               nuestros clientes, por lo que ponemos especial foco en la Seguridad de
                               la información y todo lo relacionado a ella.
                               Esta plataforma, junto con las políticas de seguridad
                               adoptadas por Portal de compra, nos permite contar con un servicio cumpliendo los
                               más altos estándares de calidad en cuanto a seguridad, disponibilidad y
                               escalabilidad de la información.

                           </p>
                       </div>
                   </article>
               </div>
           </section>
           <section class="flex justify-center desktop:justify-center">
               <div class="relative z-[1] before:absolute before:left-1/2 before:top-1/2 before:-z-[1] before:h-[330px] before:w-full before:-translate-x-1/2 before:-translate-y-1/2 before:transform before:rounded-[2.25rem] before:blur-[30px] before:content-[&#34;&#34;] before:bg-green before:opacity-20">
                   <div class="flex flex-col items-center justify-center gap-12 desktop:flex-row">
                       <img src="https://cdn.intiza.com/content/web2/public/images/ISO-27001.png" alt="ISO 27001" width="180" height="180">
                       <img src="https://cdn.intiza.com/content/web2/public/images/microsoft-azure.png" alt="Microsoft Azure" width="200" height="60">
                   </div>
               </div>
           </section>





       </main>
      
    </body>
    
    

Views/Home/indexlogueado.cshtml
@{
    ViewBag.Title = "Portal de compras";
}


<body>
    <p>@Html.ActionLink("Adjuciaciones", "Index", "AdjudicacionLicitacionProveedor", new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Cotizaciones", "Index", "LicitacionCotizacionProv", new { area = "" }, new { @class = "nav-link" })</p>
    <p> @Html.ActionLink("Licitaciones", "Index", "Licitacione", new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Organismo Licitante", "Index", "OrganismoLicitantes", new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Licitador", "Index", "Licitador", new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Proveedor", "Index", "Proveedor", new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Productos", "Index", "Producto", new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Licitaciones publicadas", "/", "ReporteLicitaciones.aspx",  new { area = "" }, new { @class = "nav-link" })</p>
    <p>@Html.ActionLink("Manage", "Index", "Manage", new { area = "" }, new { @class = "nav-link" })</p>

</body>